- imageio-openjpeg/pom.xml
- imageio-turbojpeg/pom.xml
- imageio-turbojpeg/src/main/java/de/digitalcollections/turbojpeg/Info.java
- pom.xml
With newer turbojpeg versions (tested with 2.0.) it seems that we sometimes get scaling factors that have a denominator of `0`, which will cause `DivisionByZero` errors while creating `Info` objects for images.
This PR will filter out all factors with `0` as the denominator to prevent this.
> turbojpeg: Filter out scaling factors that have 0 as the denominator

- .travis.yml
- README.md
In order to support latest changes that were introduced in 9e78e252908ccefbc01fdce36c092c768d280269 and 77724abee739b2663b718b434fc54cda4b9545e3, it is necessary to use a more recent version of `libjpeg-turbo` (at least version 1.4) in combination with JDK 8.
Thus, this PR updates the Ubuntu version for Travis CI from 14.04 to 16.04. Furthermore, all Oracle JDKs are completely removed. We rely on OpenJDK now.
> CI: remove Oracle JDKs and update Ubuntu distribution

- imageio-openjpeg/pom.xml
- imageio-turbojpeg/pom.xml
- imageio-turbojpeg/src/main/java/de/digitalcollections/turbojpeg/TurboJpeg.java
- imageio-turbojpeg/src/test/java/de/digitalcollections/turbojpeg/imageio/TurboJpegImageReaderTest.java
- pom.xml
Previously, grayscale input images would be encoded as all-white images.
> turbojpeg: Fix grayscale encoding bug

- imageio-openjpeg/src/main/java/de/digitalcollections/openjpeg/OpenJpeg.java
- imageio-openjpeg/src/main/java/de/digitalcollections/openjpeg/lib/structs/opj_image_comp.java
- imageio-openjpeg/src/test/java/de/digitalcollections/openjpeg/imageio/OpenJp2ImageReaderTest.java
This PR fixes a bug that occurs, when the input image has 16bit color depth. In these cases, the output image just contained random noise.
This PR fixes that bug and handles the conversion from 16bit to 8bit correctly.
> Handle 16bit images

- imageio-openjpeg/src/main/java/de/digitalcollections/openjpeg/OpenJpeg.java
- imageio-openjpeg/src/main/java/de/digitalcollections/openjpeg/lib/structs/opj_image.java
- imageio-openjpeg/src/test/java/de/digitalcollections/openjpeg/imageio/OpenJp2ImageReaderTest.java
> openjpeg: Take embedded ICC color profiles into account and convert accordingly

- .gitlab-ci.yml
This PR uses adds an OpenJDK 11 image with TurboJPEG to the build matrix.
> CI: Use TurboJPEG image

- imageio-openjpeg/src/main/java/de/digitalcollections/openjpeg/InStreamWrapper.java
- imageio-openjpeg/src/main/java/de/digitalcollections/openjpeg/imageio/OpenJp2ImageReader.java
If you used `reader.setInput(...)`, it would leak the memory of the previous wrapped `ImageInputStream`, leading to 1MiB of inaccessible off-heap memory.
> openjpeg: Fix potential memory leak when setting new input stream on existing reader

- imageio-openjpeg/src/main/java/de/digitalcollections/openjpeg/OpenJpeg.java
- imageio-openjpeg/src/test/java/de/digitalcollections/openjpeg/imageio/OpenJp2ImageReaderTest.java
This should be properly implemented another time by carrying over the ICC data to the ImageIO metadata.
> openjpeg: Don't convert color space (too big a performance hit)

- imageio-openjpeg/src/main/java/de/digitalcollections/openjpeg/OpenJpeg.java
- imageio-openjpeg/src/main/java/de/digitalcollections/openjpeg/lib/libopenjp2.java
@renevanderark did some performance testing of the library and noticed a performance gap between the JNR-code and his previous JNI-based approach. One difference in the access path was that he did not use wrapped bytestreams, but relied on the `opj_stream_create_default_file_stream` API to access the source images.
This PR adds two new overloads for `OpenJpeg#getInfo` and `OpenJpeg#decode` that take a `Path` argument instead of an `InputStreamWrapper` to expose this access path to the Java API.
This is mostly intended for users who use the library through the `OpenJpeg` interface and not the ImageIO APIs.
Thanks @renevanderark!
> openjpeg: Add support for direct file access (thanks @renevanderark!)

- imageio-turbojpeg/pom.xml
- imageio-turbojpeg/src/main/java/de/digitalcollections/turbojpeg/imageio/TurboJpegImageReadParam.java
- imageio-turbojpeg/src/main/java/de/digitalcollections/turbojpeg/imageio/TurboJpegImageWriterSpi.java
Guava is a big dependency that is not really needed outside of unit tests. This PR removes Guava as a dependency to use this library and restricts the scope for Guava to `test`.
> Demote guava to test dependency

- imageio-openjpeg/src/main/java/de/digitalcollections/openjpeg/OpenJpeg.java
Previously this would lead to an NPE down the road, we now fail early with an `UnsatisfiedLinkError` RTE.
> openjpeg: Throw exception when library could not be loaded (fixes #99)

- imageio-turbojpeg/src/main/java/de/digitalcollections/turbojpeg/imageio/TurboJpegImageReader.java
Logging output in `TurboJpegImageReader` uses width twice, should use width and height.
> Fix logging output (w×x instead of w×h)

- imageio-turbojpeg/src/main/java/de/digitalcollections/turbojpeg/TurboJpeg.java
- imageio-turbojpeg/src/main/java/de/digitalcollections/turbojpeg/imageio/TurboJpegImageReader.java
- imageio-turbojpeg/src/test/java/de/digitalcollections/turbojpeg/imageio/TurboJpegImageReaderTest.java
TurboJpeg expects cropping regions to be multiples of the MCU size. In some cases it was possible that the cropping region was larger than the image due to rounding artifacts (less than one MCU). This MR checks if the resulting region would exceed the image and makes it one MCU width and/or height smaller if needed.
TODO: Is it necessary to adjust the `extraCropping` to make sure it will be inside the adjusted region?
> Fix jpeg cropping edge case

- imageio-openjpeg/src/main/java/de/digitalcollections/openjpeg/imageio/OpenJp2ImageReader.java
The color scheme has been wrongly set as ARGB for JP2 images using CMYK color space. This MR makes sure CMYK is actually used in these cases.
> Fix use of CMYK for JP2 images

- imageio-openjpeg/src/main/java/de/digitalcollections/openjpeg/OpenJpeg.java
- imageio-openjpeg/src/main/java/de/digitalcollections/openjpeg/lib/libopenjp2.java
A misunderstanding in the way JNR-FFI worked led to a hard-to-debug segmentation fault crash when encoding JPEG2000 images concurrently.
The bug was in our call to `opj_image_create` during encoding. This function takes a pointer to an array of `opj_image_comptparm` structs. On the Java side, we allocated those structs through JNR-FFI's `Runtime` and passed the address of the first member of the array to the function. This was done under the assumption that the memory allocated by JNR-FFI for the array members would be the same memory that gets passed over the FFI, and, since we confirmed that JNR-FFI allocates those array members as a single contiguous memory segment, it would be safe to do so.
However, this is based on a significant misunderstanding how passing memory between the JVM …
> Fix crash during JPEG2000 encoding.

- imageio-openjpeg/src/main/java/de/digitalcollections/openjpeg/OpenJpeg.java
- imageio-openjpeg/src/main/java/de/digitalcollections/openjpeg/lib/libopenjp2.java
This is another attempt at fixing the bug mentioned in an earlier commit. The previous attempt was already headed in the right direction but didn't actually work.
This next attempt seems to be more promising, at least I couldn't trigger it when hammering my encoding test on 8 threads for ~3h, that would pretty reliably crash previously.
The gory details:
`Struct.arrayOf` allocates a continuous chunk to back an array of structures. JNR's `TransientMemoryAllocator` does not allocate memory directly for small allocations (<=256 bytes), but uses a custom page-based allocation strategy. When allocation for a new page fails, it triggers a full GC cycle and clears up all 'old and unused' pages.
However, there seems to be a bug involving concurrency and garbage collection, that leads to this …
> Fix jp2 encoding segfault, next attempt

- imageio-openjpeg/src/main/java/de/digitalcollections/openjpeg/imageio/OpenJp2ImageReader.java
This should get rid of quite a few warnings.
> jp2: When adjusting source region, always expand the area and ensure it's within the image bounds

- imageio-turbojpeg/src/test/java/de/digitalcollections/turbojpeg/imageio/TurboJpegImageReaderTest.java
This PR adds one unit test for checking the behaviour of `imageio-jnr` when dealing with one pixel height cropping:
When `imageIndex` is greater than zero, a scaled down image is used. After debugging it's shown, that the `adjustExtraCrop` method uses a scaled factor to the the height of cropped region. In that special case, `rectangle.height` is ~1.50 to `Math.round` function will return `2` for the final cropped region. (So this is no bug):
https://github.com/dbmdz/imageio-jnr/blob/fcae1bdec7b50a6375cc53147d75ee74ced845e9/imageio-turbojpeg/src/main/java/de/digitalcollections/turbojpeg/imageio/TurboJpegImageReader.java#L246-L264
In another (sub-) test we use an `imageIndex` of 0, where the library will correctly return a one pixel height cropped region.
> Wrong coordinate calculation when cropping to one pixel height

- imageio-turbojpeg/src/main/java/de/digitalcollections/turbojpeg/TurboJpeg.java
- imageio-turbojpeg/src/main/java/de/digitalcollections/turbojpeg/lib/libturbojpeg.java
turbojpeg introduced support for `abbreviated datastreams` in 2.1.4, returning early from `tjDecompressHeader3` if such a datastream is detected, and thus not updating the values for width, height colorspace and subsampling that we relied on.
This didn't cause issues with the standard ImageIO `TIFFImageReader` from the `com.sun` package, since it always completely decoded the JPEG. However, the TwelveMonkeys implementation was more efficient and only used the abbreviated datastream from the TIFF Header, as intended.
This broke our code, since we assumed that width, height, colorspace and subsampling were always available.
Luckily the fix was rather trivial: Simply check if the values were set tor not and return `null` if they weren't. The `null` info value doesn't cause any issues, since …
> turbojpeg: Fix JPEG decoding from TIFFs with versions >=2.1.4

- .github/workflows/ci.yml
The latest Ubuntu 24.04 is now available in [public demo](https://github.blog/changelog/2024-05-14-github-hosted-runners-public-beta-of-ubuntu-24-04-is-now-available/), so this PR is updating CI and uses it.
> CI: Update Ubuntu Image
